openSUSE/travel-support-program

- app/helpers/reimbursements_helper.rb
- app/models/reimbursement.rb
- app/views/reimbursements/show.pdf.prawn
- config/locales/application.en.yml
> Warning about invalid info in the PDF version of reimbursement

- app/views/events/show.html.haml
- app/views/reimbursements/show.html.haml
- app/views/reimbursements_lists/index.html.haml
- app/views/shipments/index.html.haml
- app/views/shipments/show.html.haml
- app/views/travel_sponsorships/index.html.haml
- app/views/travel_sponsorships/show.html.haml
- lib/travel_support/version.rb
Fixes #33, fixes #30, increase version.
@tsdgeos This is mainly for you, just in case you want to review. :-)
> Small fixes and release

- app/views/comments/create.js.erb
> Explicitly closing the modal after creating comment

- .travis.yml
Added the libqtwebkit-dev pacakage in travis.yml
Fixes #45
> Fix Travis build failing due to capybara-webkit

- README.md
Link for ABOUT.md and LiCENSE file
fixes #43
> Updated the links in README.md

- Gemfile.lock
- Rakefile
Added the last_comment method in rakefile
> Fix the last_comment error for rake versions above than 11.0

- app/models/ability.rb
- spec/models/ability_for_administrative_spec.rb
- spec/models/ability_for_assistant_spec.rb
- spec/models/ability_for_material_spec.rb
- spec/models/ability_for_requester_spec.rb
- spec/models/ability_for_shipper.rb
- spec/models/ability_for_supervisor_spec.rb
- spec/models/ability_for_tsp_spec.rb
Updated the ability tests and ability.rb file
> Added the ability to send email

- app/controllers/events_controller.rb
- app/helpers/events_helper.rb
- app/views/events/email.html.haml
- app/views/events/show.html.haml
- config/routes.rb
- spec/features/events_spec.rb
Added a link to email in event#show and created a method in events_helper to retrieve user emails based on state of the travel request
> Created an email view to send email to the event participants

- app/themes/bento/assets/stylesheets/bento/bootstrap_overrides.less
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
Commented the default classes for buttons in simple form intiliazers so those classes doesn't clash with the one's provided in the views
> Fixed the styling of default buttons in bento theme

- .rubocop.yml
- Gemfile
- app/helpers/application_helper.rb
- app/views/event_emails/show.html.haml
- app/views/event_mailer/event_info.html.erb
- app/views/event_mailer/event_info.html.haml
- app/views/event_mailer/event_info.text.erb
- app/views/event_mailer/event_info.text.haml
Used Redcarpet for markdown
To be rebased after #56
> Added markdown method in the application helper

- spec/helpers/events_helper_spec.rb
Added tests for the users_for_event method in event helper
> Added event helper specs

- bin/bundle
- bin/rails
- bin/rake
The bin directory which was introduced in rails 4 was missing in the application
> Added the bin directory

- app/views/event_emails/new.html.haml
Disable button after clicking on it so that multiple emails are not sent
Fixes #67
> Added disable for the event email submit button

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/routes.rb
> Added letter_opener_web to test emails

- app/views/event_emails/index.html.haml
- app/views/event_emails/new.html.haml
Also added a hint to the body field in event_email#new that it supports markdown
Fixes #68
> Added markdown for body on event_email#index

- README.md
- doc/INSTALL.MD
Removed the Getting started instructions from README.md and added them to INSTALL.md, also added a link to install file in the readme file
> Created an INSTALL.md file for TSP

- doc/INSTALL.MD
> Added doc for email support

- app/models/ability.rb
- app/models/event.rb
- app/models/user_role.rb
- spec/fixtures/event_emails.yml
- spec/fixtures/requests.yml
- spec/fixtures/state_changes.yml
- spec/fixtures/user_profiles.yml
- spec/fixtures/users.yml
- spec/helpers/events_helper_spec.rb
- spec/models/ability_for_event_organizer_spec.rb
- spec/models/has_state_mailer_spec.rb
- spec/models/reimbursable_request_mailer_spec.rb
Added tests for abilities of an event organizer, added a new user josh with the event organizer role in the users.yml and modified the other fixtures for this user
> Created ability spec file for event organizer role

- doc/ABOUT.md
Fixed the path in the ABOUT.md file for state images
Fixes #39
> Added Request_state.png in doc/html

- app/views/event_emails/new.html.haml
- spec/features/event_emails_spec.rb
Fixed the ordering and typo in event email states dropdown
> Fixed the typo in dropdown menu

- app/helpers/events_helper.rb
- spec/features/event_emails_spec.rb
- spec/helpers/events_helper_spec.rb
> Users for an event method

- app/controllers/event_emails_controller.rb
- app/controllers/event_organizers_controller.rb
> Fixed the breadcrumbs for event email and event organizer controller

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js.coffee
- app/assets/javascripts/event_organizers.js.coffee
- app/controllers/event_organizers_controller.rb
- app/models/event_organizer.rb
- app/views/event_organizers/new.html.haml
- config/routes.rb
- spec/features/event_organizers_spec.rb
- spec/models/event_organizer_spec.rb
Removed the rails4 autocomplete gem
> Added autocomplete for users with nickname and email

- app/controllers/registrations_controller.rb
- app/controllers/user_profiles_controller.rb
- app/helpers/user_profiles_helper.rb
- app/views/pages/userguide.en.html.haml
- config/initializers/devise.rb
- config/site.example.yml
- doc/ABOUT.md
- doc/USERGUIDE.md
- doc/html/UserProfilesHelper.html
- doc/html/file.ABOUT.html
- doc/html/file.USERGUIDE.html
- spec/features/comments_spec.rb
- spec/features/events_spec.rb
- spec/features/reimbursement_process_spec.rb
- spec/features/request_deadline_spec.rb
- spec/features/request_process_spec.rb
- spec/features/shipment_process_spec.rb
- spec/features/visa_letter_spec.rb
- spec/fixtures/events.yml
- spec/fixtures/requests.yml
- spec/fixtures/state_changes.yml
- spec/models/ability_for_administrative_spec.rb
- spec/models/ability_for_assistant_spec.rb
- spec/models/ability_for_material_spec.rb
- spec/models/ability_for_requester_spec.rb
- spec/models/ability_for_shipper.rb
- spec/models/ability_for_supervisor_spec.rb
- spec/models/ability_for_tsp_spec.rb
- spec/models/comment_mailer_spec.rb
- spec/models/shipment_spec.rb
Changed 'he', 'he/she', 'him', 'his' to 'their', 'they', 'theirs', 'them' and 'guy' to 'person'. And a small handful of minor grammar edits I found while searching for them, including the changing of 'customes' to the correct spelling of 'costumes'.
> Gender and grammar edits

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/stylesheets/bootstrap_init.scss
- app/assets/stylesheets/bootstrap_overrides.scss
- app/themes/bento/assets/config/manifest.js
- app/themes/bento/assets/stylesheets/bento/bootstrap_overrides.scss
- config/application.rb
- config/initializers/config.rb
This is a prerequisite for Rails 5, I split it off as its own PR as it was easier to work on it that way
> Migrate to sprockets 4

- .gitignore
- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/version.rb
- lib/travel_support/version.rb
We need to replace how the version is handled, since we are deploying from git, and not just versioned release, so this is what this PR does
> Version handling with git

- app/models/application_record.rb
> Allow sorting by id with ransack
